---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: simplego
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: flux-demo
  url: https://github.com/zball/kubernetes-kind-demo

